import Header from "./_componets/organisms/Header";
import "./globals.css";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"], weight: "400" });
export const metadata = {
  title: "Minerva Labs",
  description: "Generated by create next app",
};

const menu = [
  {
    voice: "Home",
    url: "/",
  },
  {
    voice: "Services",
    url: "/",
  },
  {
    voice: "About Us",
    url: "/",
  },
  {
    voice: "Portfolio",
    url: "/",
  },
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header menu={menu}></Header>
        {children}
      </body>
    </html>
  );
}
