import "./globals.css";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"], weight: "400" });
export const metadata = {
  title: "Minerva Labs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
